[project]
name = "git-branch-cleaner"
version = "0.1.0"
description = "CLI to safely clean stale git branches"
authors = [{name="Alex", email="ncgwzzdqfi663@hotmail.com"}]
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
gbclean = "src.gbclean:main"
